### ISSUE TITLE
Not creating resource if we delete resource

### ISSUE THREAD

**Issue by gau1991** [gavinbunney/terraform-provider-kubectl#15]
Hi,
First of all thanks alot for creating kubectl provider. We have been using this from past couple days and so far it is working fine for us.

While working I found one issue. Here is the complete use case:

We have been creating some of custom resource in our environment using this provider. So what we observed in our environment, accidently we deleted that custom resource manually using `kubectl` command. So to recreate that we ran `terraform apply` again, we received following error:

```
$ terraform apply

kubectl_manifest.test: Refreshing state... [id=/apis/testing.io/v1/namespaces/test/testservice/test

Error: failed to get resource 'TestService/test' from kubernetes: testservice.testing.io "test" not found
```

As that resource is not present our environment, the expected behaviour is it should create that.

Let me know if you need any more more information around this.

**Comment by gavinbunney** [comment]
This is mostly by normal terraform design; if you were to do the same thing with say, an AWS s3 bucket (delete it manually), next time you run plan in Terraform it would have a similar failure.

The fix for this is to remove the reference from your state files. That way, terraform won't try to refresh it and will happily create it on next run:

```bash
$ terraform state rm kubectl_manifest.test
$ terraform apply
```

Hope that helps
