### ISSUE TITLE
v1.6.1 seems to fail initilization

### ISSUE THREAD

**Issue by adamcrews** [gavinbunney/terraform-provider-kubectl#30]
When using the current version of the provider (v1.6.1) I receive the following error:

```
Error: Failed to instantiate provider "kubectl" to obtain schema: fork/exec /Users/adam/.terraform.d/plugins/terraform-provider-kubectl: exec format error
```
To produce the error, I have downloaded the provider with the 1 liner script in the docs, then simply done a `terraform validate`

**Comment by gavinbunney** [comment]
Hey @adamcrews , as part of publishing this provider to the terraform registry, I needed to update the release artifacts to now publish zip files instead of the raw binaries. Likely it is failing as from the looks of the error that you'll need to update the one-liner to support unpacking the zip. Docs are here: https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs#install-latest-version
