### ISSUE TITLE
Multi-doc yml execution order

### ISSUE THREAD

**Issue by garzillo** [gavinbunney/terraform-provider-kubectl#68]
I'm having some issues using the `kubectl_path_documents` - essentially my multi-doc yml file must be executed in order , but right now it's happening in some other order. Is there some way to force the documents to be applied in order?

Here's a representative snippet that I'm using - 

```
data "kubectl_path_documents" "example" {
  pattern = "./multi-doc.yml"
}
resource "kubectl_manifest" "example" {
  wait = true
  count     = length(data.kubectl_path_documents.example.documents)
  yaml_body = element(data.kubectl_path_documents.example.documents, count.index)
}
```

**Comment by mhenniges** [comment]
This is plaguing me as well. The correct sort order is well known (a specific sort by kind), and I think there is a method in the client go that would do it, or absent a code change in this provider you could work around it partially by calling out to something like [ksort](https://github.com/superbrothers/ksort). However, that's not the only problem. I have my manifests correctly sorted by kind, and run them in a loop similar to yours, and it still fails sometimes, because the items are created in parallel. For example, even though the namespace object is the first  one in my list, there is no guarantee that it will finish creating before all the other requests get there, so I sometimes have failures about namespace existing.

I think the complete solution to this relies on having a way to sort them in order, combined with a way to have the ordered apply block at certain points to ensure later objects don't fail.

**Comment by stawik-mesa** [comment]
Have you already tried to set the `apply_retry_count` (to a higher number).

provider "kubectl" {
  apply_retry_count = 15
}

This worked for me ;)

**Comment by diegofrata** [comment]
If I am not mistaken files are applied in the alphabetical order, you could try naming files something like 01_, 02_, etc. Or just retry like @stawik-mesa suggested -- that's kind of what I am doing as well. If you really have a strong requirement for applying files in order, you can also have then as separate resources and use depends_on between the resources to force the order.

**Comment by gavinbunney** [comment]
Unfortunately this is a symptom of how terraform runs the counts in parallel. You can force it to run things once at a time via `--parallel` but I wouldn't recommend that as it's incredibly slow!

The two approachs are as @stawik-mesa mentioned to use `apply_retry_count` or alternatively split your yaml docs into differnet sets. I do that for a bunch of large projects where I have CRDs defined in `01-crds.yaml`, apply that, then have `02-src.yaml` which requires the crds. You can then make two different `kubectl_manifest` resources which depend on each other to ensure the ordering is respected.

e.g.

```hcl
data "kubectl_path_documents" "crd" {
  pattern = "./01-*.yaml"
}

resource "kubectl_manifest" "crd" {
  wait = true
  count     = length(data.kubectl_path_documents.crd.documents)
  yaml_body = element(data.kubectl_path_documents.crd.documents, count.index)
}

data "kubectl_path_documents" "deployment" {
  pattern = "./02-*.yaml"
}

resource "kubectl_manifest" "deployment" {
  wait = true
  count     = length(data.kubectl_path_documents.deployment.documents)
  yaml_body = element(data.kubectl_path_documents.deployment.documents, count.index)
  depends_on = [kubectl_manifest.crd]
}
```
