### ISSUE TITLE
Option for preventing existing configuration from being overwritten unintentionally

### ISSUE THREAD

**Issue by MarcinGrinberg** [gavinbunney/terraform-provider-kubectl#73]
Hi,

I'm thinking about an improvement.

It happened to me sometimes when writing deployment using kubectl provider that I've unintentionally updated some other shared resource. I know that it is a default behaviour of kubectl apply (it is not looking if the resource already exists) and that is fine because it doesn't have any state information either way.

I was thinking if with this provider we could think of enhancement like a flag "check_if_exists" which would enable a check that would work like that:
- if the configuration is already in state and object we're trying to create already exists in the cluster would raise an error.

Could default to false keeping backward compatibility.

What do you guys think?

Thanks,
Marcin

**Comment by gavinbunney** [comment]
Hi @MarcinGrinberg that's definitely something that's doable. I'll likely not add it in the near future, but feel free to submit a PR. An approach might be to change from using an `apply` to a `create` approach; kubectl today does mostly what you are talking about when you run `kubectl create` it will refuse to inplace update existing resources.

**Comment by jbg** [comment]
Hi @gavinbunney, is this closed because you decided against using `kubectl create` for the create operation?

The current behaviour when trying to create a resource that already exists is a bit surprising (disagrees with TF's design and differs from how all other providers work) and can in some cases lead to quite subtle problems. For example, if you have multiple kubectl provider definitions for multiple clusters, and you accidentally specify the wrong provider for a new resource, if the resource already exists in the real world but not in the state any other provider would raise an error when trying to create it, but the `kubectl` provider will silently succeed and you'll end up with multiple TF resources corresponding to the same real-world resource.

I don't really see a downside to moving to `kubectl create`; the difference would be that `terraform import` would now be required to bring a resource created outside of Terraform into the state, which is the case for all other providers, so it's already something people need to be familiar with.
